# Generated by Django 5.1.2 on 2024-10-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shelter_photos/')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shelter',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('photo', models.ImageField(blank=True, null=True, upload_to='dog_photos/')),
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('수컷', '수컷'), ('암컷', '암컷'), ('중성', '중성')], max_length=10)),
                ('tags', models.CharField(max_length=255)),
                ('remaining_days', models.IntegerField()),
                ('description', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barameong.shelter')),
            ],
            options={
                'db_table': 'dog',
            },
        ),
    ]
